"use client";
/* The public payload is resolved after mount from the tokenized API route. */
/* eslint-disable react-hooks/set-state-in-effect */

import { ArrowLeft, ChatCircleDots, PaperPlaneTilt, WarningCircle } from "@phosphor-icons/react";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { backend } from "@/lib/backend/client";
import type { SharedBoardPayload } from "@/lib/backend/types";
import { frontendErrorMessage, readBackendError } from "@/lib/frontend-errors";

type Payload = SharedBoardPayload & { assetsConfigured: boolean };
export function SharedBoardScreen({ token }: { token: string }) {
  const [payload, setPayload] = useState<Payload | null>(null); const [status, setStatus] = useState<"loading" | "ready" | "missing" | "expired" | "error">("loading"); const [message, setMessage] = useState(""); const [body, setBody] = useState(""); const [requiresAuth, setRequiresAuth] = useState(false);
  const load = async () => { try { const response = await fetch(`/api/shared/${encodeURIComponent(token)}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) { setStatus(response.status === 410 ? "expired" : response.status === 404 ? "missing" : "error"); setMessage(data.error?.message ?? "No pudimos abrir este tablero."); return; } setPayload(data); setStatus("ready"); } catch { setStatus("error"); setMessage("No pudimos conectar con la vista compartida."); } };
  useEffect(() => { void load(); }, [token]); // eslint-disable-line react-hooks/exhaustive-deps
  const offsets = useMemo(() => { const map = new Map<string, number>(); let cursor = 0; payload?.sections.forEach((section) => { map.set(section.id, cursor); cursor += Number(section.width) + 28; }); return { map, width: cursor + 80 }; }, [payload]);
  if (status !== "ready" || !payload) return <main className="terminal-page"><section className="terminal-card"><div className="auth-wordmark">MOODBOARD</div><WarningCircle size={30} /><h1>{status === "loading" ? "Abriendo tablero" : status === "expired" ? "Este enlace expiró" : status === "missing" ? "Vista no disponible" : "No pudimos abrir la vista"}</h1><p>{status === "loading" ? "Estamos preparando las imágenes y comentarios." : status === "missing" ? "El enlace fue revocado o ya no existe. Solicita una nueva vista al equipo del proyecto." : message}</p><Link className="text-action" href="/">Volver al inicio</Link></section></main>;
  if (!payload.assetsConfigured) return <main className="terminal-page"><section className="terminal-card"><WarningCircle size={30} /><h1>Las imágenes no están disponibles</h1><p>La vista existe, pero el servicio de activos privados no está configurado. El equipo administrador debe revisar la variable server-only de Supabase.</p></section></main>;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await backend.createSharedComment({ token, body }); setBody(""); setRequiresAuth(false); setMessage("Comentario publicado."); await load(); } catch (cause) { const mapped = readBackendError(cause); setRequiresAuth(mapped.code === "UNAUTHORIZED"); setMessage(mapped.code === "UNAUTHORIZED" ? "Ingresa a tu cuenta para comentar en esta vista." : frontendErrorMessage(cause, "No pudimos publicar.")); } };
  return <div className="shared-shell"><header className="shared-header"><div><span className="auth-wordmark">MOODBOARD</span><span className="shared-badge">Vista de revisión</span></div><div><strong>{payload.project.name}</strong><span>{payload.board.name}</span></div><Link href="/"><ArrowLeft size={16} /> Ir al espacio de trabajo</Link></header>
    <main className="shared-main"><div className="shared-canvas"><div className="shared-world" style={{ width: offsets.width, height: 1040 }}>{payload.sections.map((section, index) => <section className="board-section" key={section.id} style={{ left: offsets.map.get(section.id), width: Number(section.width) }}><header className="section-heading"><span>{String(index + 1).padStart(2, "0")}</span><h2>{section.name.toLocaleUpperCase("es")}</h2></header></section>)}{payload.items.map((item) => { const left = (offsets.map.get(String(item.section_id)) ?? 0) + Number(item.x); const style = { left, top: Number(item.y), width: Number(item.width), height: Number(item.height) }; return <article className={`board-card board-card-${String(item.type)}`} key={String(item.id)} style={style}>{item.type === "image" && item.image_url ? <><Image className="card-image" src={String(item.image_url)} alt={String(item.title || "Referencia visual")} fill unoptimized sizes="320px" /><div className="image-caption">{String(item.title || "")}</div></> : null}{item.type === "note" ? <div className="note-content"><strong>{String(item.title || "Nota")}</strong><p>{String(item.content || "")}</p></div> : null}{item.type === "palette" && Array.isArray(item.colors) ? <div className="palette-content"><strong>{String(item.title || "Paleta")}</strong><div className="swatches">{item.colors.map((color) => <span key={String(color)} style={{ backgroundColor: String(color) }} />)}</div></div> : null}</article>; })}</div></div>
      <aside className="shared-comments"><span className="drawer-kicker">Conversación</span><h1>{payload.comments.length} comentarios</h1><div>{payload.comments.map((comment) => <article key={comment.id}><strong>{comment.author?.display_name || "Colaborador"}</strong><p>{comment.body}</p></article>)}</div>{payload.permission === "comment" ? <form onSubmit={submit}><label><span className="visually-hidden">Comentario</span><textarea name="shared-comment" required maxLength={4000} value={body} onChange={(event) => setBody(event.target.value)} placeholder="Escribe una observación…" /></label><button className="share-button" disabled={!body.trim()}><PaperPlaneTilt size={16} /> Comentar</button></form> : <p className="shared-readonly"><ChatCircleDots size={17} /> Esta vista es de solo lectura.</p>}{message ? <p className="inline-feedback" role="status">{message}</p> : null}{requiresAuth ? <Link className="text-action" href={`/auth?next=${encodeURIComponent(`/share/${token}`)}`}>Ingresar para comentar</Link> : null}</aside>
    </main></div>;
}
